use_frameworks!

platform :ios, '12.0'

target 'HCScaffold_Example' do
  pod 'HCScaffold', :path => '../'

  target 'HCScaffold_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
